// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi_A7ZXayWAPBwGbv3cF27gaRXKlx1XiA',
    appId: '1:878978476421:web:9f0c941a97eba1f7ea7cec',
    messagingSenderId: '878978476421',
    projectId: 'hary-mood-tracker-final',
    authDomain: 'hary-mood-tracker-final.firebaseapp.com',
    storageBucket: 'hary-mood-tracker-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvtHfMTsljwc0fagjtThap-qunh9o17Es',
    appId: '1:878978476421:android:da6d266927b9984aea7cec',
    messagingSenderId: '878978476421',
    projectId: 'hary-mood-tracker-final',
    storageBucket: 'hary-mood-tracker-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0y3BygofYfcYncYoAHpXXdNTKoPq_KB4',
    appId: '1:878978476421:ios:e8bc5622bb0f2aa5ea7cec',
    messagingSenderId: '878978476421',
    projectId: 'hary-mood-tracker-final',
    storageBucket: 'hary-mood-tracker-final.appspot.com',
    iosBundleId: 'com.example.finalProjectTiktokClone',
  );

}